apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-airbyte # ingress name
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost # host, example: airbyte.company.example
    http:
      paths:
      - backend:
          service:
            # format is ${RELEASE_NAME}-airbyte-webapp-svc
            name: f1toolbox-airbyte-airbyte-webapp-svc
            port:
              number: 80 # service port, example: 8080
        path: /
        pathType: Prefix
