apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: f1toolbox-core
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: "dagster.f1toolbox.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: f1toolbox-dagster-dagster-webserver-read-only
            port:
              number: 80
  - host: "airbyte.f1toolbox.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            # format is ${RELEASE_NAME}-airbyte-webapp-svc
            name: f1toolbox-airbyte-airbyte-webapp-svc
            port:
              number: 80 # service port, example: 8080
