#https://github.com/dagster-io/dagster/blob/master/helm/dagster/charts/dagster-user-deployments/values.yaml
dagster-user-deployments:
  enabled: true
  deployments:
    - name: "f1toolbox-core"
      image:
        repository: "leobocci/f1toolbox-dagster"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "-f"
        - "/app/src/dagster/definitions.py"
      port: 8081
      serviceAccount:
        create: false
        name: dagster-ksa
        namespace: f1toolbox-core