dagster-user-deployments:
  enabled: true
  deployments:
    - name: "f1toolbox-core"
      image:
        repository: "leobocci/f1toolbox-dagster"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "-f"
        - "/app/src/dagster/definitions.py"
      port: 8081