#default values: https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/values.yaml
global:
  auth:
    enabled: true
    cookieSecureSetting: "false"
  server:
    livenessProbe:
      initialDelaySeconds: 90
  airbyteUrl: "airbyte.104.154.59.130.nip.io"
  secretsManager:
    type: googleSecretManager
    secretManagerSecretName: airbyte-config-secrets
    googleSecretManager:
      projectId: f1toolbox-core
      credentialsSecretKey: gcp.json
  storage:
    type: "GCS"
    storageSecretName: airbyte-config-secrets
    bucket:
      log: airbyte-state-bucket
      state: airbyte-state-bucket
      workloadOutput: airbyte-state-bucket
    gcs:
      projectId: f1toolbox-core
      credentialsPath: /secrets/gcs-log-creds/gcp.json
