repositories:
  - name: dagster
    url: https://dagster-io.github.io/helm
  - name: airbyte
    url: https://airbytehq.github.io/helm-charts

releases:
  - name: f1toolbox-airbyte
    namespace: f1toolbox-core
    chart: ./charts/airbyte
    version: 1.1.0
    values:
      - ./values/airbyte.yaml

  - name: f1toolbox-dagster
    namespace: f1toolbox-core
    chart: ./charts/dagster
    version: 1.8.11
    values:
      - ./values/dagster.yaml
